name: Prepare Release PR

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to prepare for'
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Get next version
        id: get_version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use semantic-release to get next version without creating tags
          NEXT_VERSION=$(uv run semantic-release version --print 2>/dev/null || echo "")
          
          if [ -n "$NEXT_VERSION" ]; then
            echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
            echo "has_version=true" >> $GITHUB_OUTPUT
          else
            echo "has_version=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR title
        if: steps.get_version.outputs.has_version == 'true' && contains(github.event.pull_request.title, 'release')
        run: |
          PR_NUMBER=${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          NEW_TITLE="release: v${{ steps.get_version.outputs.next_version }}"
          
          gh pr edit $PR_NUMBER --title "$NEW_TITLE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create version tag on dev branch
        if: steps.get_version.outputs.has_version == 'true'
        run: |
          NEXT_VERSION=${{ steps.get_version.outputs.next_version }}
          
          # Create and push tag on dev branch
          git tag "v$NEXT_VERSION"
          git push origin "v$NEXT_VERSION"
          
          echo "Created tag v$NEXT_VERSION on dev branch"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: steps.get_version.outputs.has_version == 'true'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          NEXT_VERSION=${{ steps.get_version.outputs.next_version }}
          
          gh pr comment $PR_NUMBER --body "🔍 Next release version will be: **v$NEXT_VERSION**

Tag \`v$NEXT_VERSION\` has been created on dev branch and will be synced to main after merge."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}