name: Sync Tags

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    branches: [main]

jobs:
  sync-tags:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Ensure tag visibility for future dev branches
        run: |
          # RC tags are now synced during release workflow
          # This step ensures any remaining tags are available
          git fetch --tags
          git push --tags || true
          echo "Post-release tag synchronization completed"